<!doctype html><html lang="zh-Hans"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>示例课程 · 学习资料整理</title><style>
*{box-sizing:border-box}body{margin:0;font:16px -apple-system,BlinkMacSystemFont,sans-serif;background:#f5f7fa;color:#243746}nav{height:68px;padding:0 40px;background:white;border-bottom:1px solid #e0e6ee;display:flex;align-items:center;gap:32px}nav strong{color:#1867ae;font-size:20px}.tag{margin-left:auto;color:#778899;font-size:13px}main{margin:34px 510px 40px 44px;min-width:480px}.crumb{color:#6c7e8d;font-size:14px}h1{font-size:29px;line-height:1.3;letter-spacing:-.6px;margin:15px 0}p.intro{color:#617487;font-size:14px;line-height:1.7}.section{background:white;border:1px solid #e0e6ee;border-radius:12px;margin-top:20px;list-style:none;padding:18px 22px}.sectionname{font-size:18px;margin:0 0 12px}.activity{list-style:none;padding:13px 0;border-top:1px solid #edf0f4;display:flex;align-items:center;gap:14px}.activity a{color:#1267ac;text-decoration:none;font-size:16px}.activityicon{width:34px;height:34px}.accesshide{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}.detail{font-size:12px;color:#6d7d8b;margin-top:5px}.badge{font-size:11px;background:#f7eef4;color:#ad4089;padding:7px;border-radius:5px;width:34px;text-align:center}.note{font-size:12px;color:#6d7d8b;line-height:1.6}ul{padding:0;margin:0}
</style><body class="course-view-topics"><nav><strong>学习资料整理</strong><span>课程</span><span>学习资源</span><span class="tag">示例课程 · 标准 Moodle 结构</span></nav><main id="region-main"><div class="course-content"><div class="crumb">我的课程 / 示例课程</div><h1>设计与协作基础</h1><p class="intro">集中查看课程材料，按需保存到本地。<br>以下为原创示例资料，不包含真实学校、教师或学生信息。</p><ul><li class="section"><h3 class="sectionname">课程介绍</h3><ul>
<li class="activity modtype_resource" data-id="101" data-activityname="课程学习指南.pdf"><img class="activityicon" src="../theme/image.php/demo/core/f/pdf" alt=""><a href="../pluginfile.php/1/mod_resource/content/101/guide.pdf"><span class="instancename">课程学习指南.pdf<span class="accesshide"> File</span></span></a></li>
<li class="activity modtype_resource" data-id="102" data-activityname="第一章 · 设计思维.pptx"><img class="activityicon" src="../theme/image.php/demo/core/f/powerpoint" alt=""><a href="../pluginfile.php/1/mod_resource/content/102/slides.pptx"><span class="instancename">第一章 · 设计思维.pptx</span></a></li>
<li class="activity modtype_resource" data-id="103" data-activityname="小组协作模板.docx"><img class="activityicon" src="../theme/image.php/demo/core/f/document" alt=""><a href="../pluginfile.php/1/mod_resource/content/103/template.docx"><span class="instancename">小组协作模板.docx</span></a></li>
</ul></li><li class="section"><h3 class="sectionname">实践资料</h3><ul>
<li class="activity modtype_resource" data-id="104" data-activityname="项目安排.csv"><img class="activityicon" src="../theme/image.php/demo/core/f/spreadsheet" alt=""><a href="../pluginfile.php/1/mod_resource/content/104/schedule.csv"><span class="instancename">项目安排.csv</span></a></li>
<li class="activity modtype_resource" data-id="105" data-activityname="流程示意图.svg"><img class="activityicon" src="../theme/image.php/demo/core/f/image" alt=""><a href="../pluginfile.php/1/mod_resource/content/105/workflow.svg"><span class="instancename">流程示意图.svg</span></a></li>
<li class="activity modtype_resource" data-id="106" data-activityname="阅读笔记.txt"><img class="activityicon" src="../theme/image.php/demo/core/f/text" alt=""><a href="../pluginfile.php/1/mod_resource/content/106/notes.txt"><span class="instancename">阅读笔记.txt</span></a></li>
</ul></li><li class="section"><h3 class="sectionname">课程活动</h3><ul><li class="activity modtype_assign"><span class="badge">↑</span><div><a href="/mod/assign/view.php?id=201">作业 1 · 提交入口</a><div class="detail">提交活动 · 不纳入文件清单</div></div></li><li class="activity modtype_questionnaire"><span class="badge">☷</span><a href="/mod/questionnaire/view.php?id=202">课堂反馈问卷</a></li><li class="activity modtype_url"><span class="badge">↗</span><a href="/mod/url/view.php?id=203">延伸阅读网站</a></li></ul></li></ul><p class="note">公开审核演示：原创文件与标准 Moodle File 结构，不包含真实学校、教师、学生或账号信息。</p></div></main></body></html>
